- package-lock.json
Adicionando isntalações do npm e uma pasta components como teste no front-end
> ESTRUTURA - Adicionanod instalaçoes front/back

- README.md
- back-end/.env.example
- back-end/src/database/migrations/20211109201714-User.js
- back-end/src/database/migrations/20211109201719-Product.js
- back-end/src/database/migrations/20211109201728-Sale.js
- back-end/src/database/migrations/20211109201740-SalesProduct.js
- back-end/src/database/models/products.js
- back-end/src/database/models/sales.js
- back-end/src/database/models/salesProducts.js
- back-end/src/database/models/user.js
- package-lock.json
Req0 Feat: Gerando Sequelize; Criando Models e Migration das tabelas User,Product, Sale, SalesProduct
> Main group 12 (Sequelize Start)

- back-end/src/database/migrations/20211110175520-create-users.js
- back-end/src/database/migrations/20211110180844-create-sales.js
- back-end/src/database/migrations/20211110181746-create-products.js
- back-end/src/database/migrations/20211110183336-create-sales-products.js
- back-end/src/database/models/Product.js
- back-end/src/database/models/Sale.js
- back-end/src/database/models/SalesProduct.js
- back-end/src/database/models/User.js
- back-end/src/database/models/Users.js
- front-end/package-lock.json
- front-end/package.json
- package-lock.json
> [MAIN GROUP 8] [BACK] [FEAT] [SEQUELIZE-SETUP]

- back-end/src/database/seeders/20211110204251-Sellers.js
- back-end/src/database/seeders/20211110205314-Customers.js
- back-end/src/database/seeders/20211110205738-Products.js
- back-end/src/database/seeders/20211110210959-Sales.js
- back-end/src/database/seeders/20211110211648-SalesProducts.js
- back-end/src/database/seeders/20211110212039-Admin.js
> [MAIN GROUP 8] [BACK] [FEAT] [CREATE - SEEDERS]

- README.md
- front-end/src/components/NavBar.jsx
- front-end/src/components/ProductCard.jsx
- front-end/src/components/ProductTableListCard.jsx
- front-end/src/components/StatusProductCard.jsx
- front-end/src/components/UserTableListCard.jsx
> [MAIN GROUP 8] [FRONT] [FEAT] [GENERAL COMPONENTS]

- back-end/package-lock.json
- back-end/package.json
- back-end/src/api/app.js
- back-end/src/database/controllers/userController.js
- back-end/src/database/models/SalesProduct.js
- back-end/src/database/models/User.js
- back-end/src/database/services/userService.js
- front-end/src/App.js
- front-end/src/pages/Login.jsx
> [MAIN GROUP 8][FEAT][LOGIN][VS2]

- front-end/src/components/EmailInput.jsx
- front-end/src/components/PasswordInput.jsx
- front-end/src/helpers/validation/index.js
- front-end/src/helpers/validation/validateEmail.js
- front-end/src/helpers/validation/validatePassword.js
- front-end/src/pages/Login.jsx
- front-end/src/store/index.js
- Finalizado o Requisito 3
- Adicionado useEffect à página de login para a atualização dos campos de email e senha
- Adicionados os Helpers validateEmailFormat e validatePassword
> [X] Requisito 3

- front-end/src/App.js
- front-end/src/components/drinkCard.js
- front-end/src/components/menu.js
- front-end/src/components/navBar.js
- front-end/src/components/shoppingCartStatus.js
- front-end/src/context/productContext.js
- front-end/src/context/provider.js
`03customer_products.test`
- Estilização praticamente removida.
- Configurações de roda movida do server.js para o app.js no backend
- Ao realizar o login, os dados do usuário, assim como o token de autenticação, são salvos no localStorage
> [GRUPO 1] - Tela de produtos

- back-end/package-lock.json
- back-end/package.json
- back-end/src/api/app.js
- back-end/src/app/controllers/loginController.js
- back-end/src/app/services/loginService.js
- back-end/src/middlewares/loginValidations.js
- back-end/src/routes/loginRouter.js
> [Main group 11] [refactoring login functions]

- back-end/src/app/controllers/loginController.js
- back-end/src/app/services/loginService.js
fix - adicionando hash no login
> [main-group-11][login-backend][hash]

- front-end/src/App.js
- front-end/src/components/RegisterButton.jsx
- front-end/src/helpers/validations.js
- front-end/src/pages/Login.jsx
refatora o frontend do projeto, requisitos 1 a 10, apaga código comentado e repetitivo. Cria pasta helpers com funções compartilhadas pelas páginas de login e registro. Código mais enxuto e organizado.
> [refactor] [req 1 - 10] [create helpers directory]

- back-end/src/api/app.js
- back-end/src/api/controllers/saleController.js
- back-end/src/api/controllers/userController.js
- back-end/src/api/routers/index.js
- back-end/src/api/routers/saleRouter.js
- back-end/src/api/routers/userRouter.js
- back-end/src/api/services/saleService.js
- back-end/src/api/services/userService.js
- back-end/src/database/migrations/20211109193309-create-sales.js
- back-end/src/database/migrations/20211109195913-create-sales-products.js
- back-end/src/database/models/product.js
- back-end/src/database/models/sale.js
- back-end/src/database/models/saleProduct.js
- front-end/src/App.js
- front-end/src/components/deliveryDetails.js
- front-end/src/components/drinkCard.js
- front-end/src/components/orderCheckout.js
- front-end/src/components/tableOrder.js
- front-end/src/components/tableOrderBody.js
- front-end/src/context/provider.js
- front-end/src/pages/Checkout.js
- front-end/src/pages/Login.js
- front-end/src/pages/index.js
- front-end/src/services/saleAPI.js
- front-end/src/services/userAPI.js
```04customer_checkout.test```
- Nova tela de adicionada no frontend (checkout)
- Agora o `id` do usuário também é salvo no localStorage ao efetuar o login
- Novo enpoint POST /sales para cadastro de uma nova venda
- este enpoint atualiza as tabelas `sale` e `salesProducts`
- Alteração da nomeclatura de model (~~saleProduct~~ > salesProducts)
- Corrigida associação de tabelas no model `salesProducts`
- Configurado arquivo `frontend/src/pages/index.js` para exportação das paginas no frontend
> [GRUPO 1] - Tela de checkout

- back-end/src/database/models/product.js
- back-end/src/database/models/sale.js
- back-end/src/database/models/saleproduct.js
- back-end/src/database/models/user.js
Inserção de propriedade tableName em todos os models.
> [ Main Group 2 ] [ Hotfix ] [ Back End ] [ Req 0: Sequelize Fix ] 

- back-end/package-lock.json
- back-end/src/api/auth/validateJWT.js
- back-end/src/api/routers/saleRouter.js
- back-end/yarn.lock
- front-end/package-lock.json
- front-end/src/components/userList.js
- front-end/src/pages/Admin.js
Configura middleware de validação de token JWT na rota POST  /sales
> [GRUPO 1] - Validate JWT

- front-end/src/App.js
- front-end/src/pages/Checkout.jsx
Nesse PR foi criado apenas a estrutura da página de checkout com os data-testid's de cada elemento
> [ Main Group 2 ] [ Feature ] [ Front ] [ Checkout ] 

- front-end/src/App.css
- front-end/src/App.js
- front-end/src/pages/OrderDetails.jsx
Nesse PR foi criada apenas a estrutura da página de detalhes do pedido (ainda falta a implementação da lógica para o requisito passar)
> [ Main Group 2 ] [ Feature ] [ Front-End ] [ Order Details ]

- front-end/src/App.js
- front-end/src/components/DetailsAndAddress.jsx
- front-end/src/components/FinishOrderButton.jsx
- front-end/src/components/RenderOrders.jsx
- front-end/src/components/TotalPrice.jsx
- front-end/src/context/ContextProvider.js
- front-end/src/pages/Checkout.jsx
requisitos 17 a 21 em andamento...
> Main group 13 feat checkout

- back-end/src/api/app.js
- back-end/src/controllers/products.js
> [ Main Group 2 ] [ Hotfix ] [ Back End ] [ Req 11: Tradução da rota '/cliente/produtos' de PTB para ING ]

- back-end/src/routes/userRouter.js
- front-end/src/helpers/validRegister.js
- front-end/src/pages/Administrator/Management/index.jsx
fix - finalizando requisito 40 e adicionando isvalid no helper
> [MAIN-GROUP-11][REQ-40]

- __tests__/config/matchers/puppeteer/toWaitReqFinished.js
O teste deveria alterar a constante que está sendo importada ou ele deveria apenas ler?
> fix: Remove .trim

- back-end/src/api/Controllers/saleController.js
- back-end/src/api/Services/saleService.js
- back-end/src/api/routes/sale.js
- back-end/src/database/models/salesProduct.js
Criação de 2 endpoints
- `GET /sales/:id` - retorna os dados necessários para a tela de detalhes do pedido tanto cliente quanto vendedor
- `PATCH /sales/:id` - atualiza o status do pedido ao passar `{ status: "valor do status" }` como payload
> [MAIN GROUP 6] [Sale endpoints]

- front-end/package-lock.json
- front-end/package.json
- front-end/src/components/Card.jsx
- front-end/src/components/NavBar.jsx
> [ Main Group 2 ] [ Removendo material UI ]

- __tests__/end-to-end/03customer_products.test.js
- back-end/src/database/controller/loginController.js
- back-end/src/database/service/index.js
- back-end/src/database/service/jwt.js
- front-end/package-lock.json
- front-end/package.json
- front-end/src/components/ButtonSeeCart.jsx
- front-end/src/components/Chechout/TableItens.jsx
- front-end/src/components/Login/Form.jsx
- front-end/src/components/NavBar.jsx
- front-end/src/components/ProductCard.jsx
- front-end/src/context/LoginProvider.jsx
- front-end/src/index.css
- front-end/src/pages/customer/Products.jsx
- front-end/src/routes/routes.js
- Cria botão de carrinho com preço total do pedido
- Ao clicar redireciona para o tela de checkout
> [ Main group 4 ] -  fluxo cliente req16

- __tests__/end-to-end/11admin_manage_users.test.js
- front-end/src/components/TableUsers/index.jsx
- front-end/src/pages/Administrator/Management/index.jsx
fix - finalizando requisito 43
> [MAIN-GROUP-11][REQ 43]
